name: Optimize images

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.gif'

jobs:
  crush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Optimize images with Crush.pics
        uses: crush-pics/crush-pics-github-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.CRUSH_API_KEY }}